#!/bin/bash
CONFIGURATION=Debug
# CONFIGURATION=Release

if [ -d build/${CONFIGURATION} ] 
then
  echo build/${CONFIGURATION} not found
  exit 1
fi

sudo cp -r build/${CONFIGURATION}/zfs.kext /System/Library/Extensions
sudo cp -r build/${CONFIGURATION}/zfs.fs /System/Library/Filesystems
sudo cp -r build/${CONFIGURATION}/zfs /usr/sbin
sudo cp -r build/${CONFIGURATION}/zpool /usr/sbin
sudo cp -r build/${CONFIGURATION}/libzfs.dylib /usr/lib
